// TODO: Insert description here. (generated by jaebong)

#ifndef BAZEL_ESP_EXTERNAL_ISTIO_PROXY_GIT_CONTRIB_ENDPOINTS_SRC_API_MANAGER_QUOTA_CONTROL_H_
#define BAZEL_ESP_EXTERNAL_ISTIO_PROXY_GIT_CONTRIB_ENDPOINTS_SRC_API_MANAGER_QUOTA_CONTROL_H_

#include "contrib/endpoints/include/api_manager/utils/status.h"
#include "contrib/endpoints/src/api_manager/context/request_context.h"

namespace google {
namespace api_manager {

// Call service control quota.
void QuotaControl(std::shared_ptr<context::RequestContext>,
                         std::function<void(utils::Status)>);

}  // namespace api_manager
}  // namespace google

#endif  // BAZEL_ESP_EXTERNAL_ISTIO_PROXY_GIT_CONTRIB_ENDPOINTS_SRC_API_MANAGER_QUOTA_CONTROL_H_
