// TODO: Insert description here. (generated by jaebong)

#include <contrib/endpoints/src/api_manager/quota_control.h>

#include "testing/base/public/gunit.h"

namespace google {
namespace service_control_client {
namespace {

TEST(quota_service_control, Test1) {
  // TODO(jaebong): Auto-generated test stub
}

}  // namespace
}  // namespace service_control_client
}  // namespace google
