include_directories(
        src/protobuf/src
)

set(PROTOBUF_SRC
        src/protobuf/src/google/protobuf/io/coded_stream.cc
        src/protobuf/src/google/protobuf/io/coded_stream.h
        src/protobuf/src/google/protobuf/io/coded_stream_inl.h
        src/protobuf/src/google/protobuf/io/gzip_stream.cc
        src/protobuf/src/google/protobuf/io/gzip_stream.h
        src/protobuf/src/google/protobuf/io/package_info.h
        src/protobuf/src/google/protobuf/io/printer.cc
        src/protobuf/src/google/protobuf/io/printer.h
        src/protobuf/src/google/protobuf/io/strtod.cc
        src/protobuf/src/google/protobuf/io/strtod.h
        src/protobuf/src/google/protobuf/io/tokenizer.cc
        src/protobuf/src/google/protobuf/io/tokenizer.h
        src/protobuf/src/google/protobuf/io/zero_copy_stream.cc
        src/protobuf/src/google/protobuf/io/zero_copy_stream.h
        src/protobuf/src/google/protobuf/io/zero_copy_stream_impl.cc
        src/protobuf/src/google/protobuf/io/zero_copy_stream_impl.h
        src/protobuf/src/google/protobuf/io/zero_copy_stream_impl_lite.cc
        src/protobuf/src/google/protobuf/io/zero_copy_stream_impl_lite.h
        src/protobuf/src/google/protobuf/stubs/atomic_sequence_num.h
        src/protobuf/src/google/protobuf/stubs/atomicops.h
        src/protobuf/src/google/protobuf/stubs/atomicops_internals_arm64_gcc.h
        src/protobuf/src/google/protobuf/stubs/atomicops_internals_arm_gcc.h
        src/protobuf/src/google/protobuf/stubs/atomicops_internals_arm_qnx.h
        src/protobuf/src/google/protobuf/stubs/atomicops_internals_atomicword_compat.h
        src/protobuf/src/google/protobuf/stubs/atomicops_internals_generic_c11_atomic.h
        src/protobuf/src/google/protobuf/stubs/atomicops_internals_generic_gcc.h
        src/protobuf/src/google/protobuf/stubs/atomicops_internals_mips_gcc.h
        src/protobuf/src/google/protobuf/stubs/atomicops_internals_power.h
        src/protobuf/src/google/protobuf/stubs/atomicops_internals_ppc_gcc.h
        src/protobuf/src/google/protobuf/stubs/atomicops_internals_solaris.h
        src/protobuf/src/google/protobuf/stubs/atomicops_internals_tsan.h
        src/protobuf/src/google/protobuf/stubs/atomicops_internals_x86_gcc.cc
        src/protobuf/src/google/protobuf/stubs/atomicops_internals_x86_gcc.h
        src/protobuf/src/google/protobuf/stubs/atomicops_internals_x86_msvc.cc
        src/protobuf/src/google/protobuf/stubs/atomicops_internals_x86_msvc.h
        src/protobuf/src/google/protobuf/stubs/bytestream.cc
        src/protobuf/src/google/protobuf/stubs/bytestream.h
        src/protobuf/src/google/protobuf/stubs/callback.h
        src/protobuf/src/google/protobuf/stubs/casts.h
        src/protobuf/src/google/protobuf/stubs/common.cc
        src/protobuf/src/google/protobuf/stubs/common.h
        src/protobuf/src/google/protobuf/stubs/fastmem.h
        src/protobuf/src/google/protobuf/stubs/hash.h
        src/protobuf/src/google/protobuf/stubs/int128.cc
        src/protobuf/src/google/protobuf/stubs/int128.h
        src/protobuf/src/google/protobuf/stubs/logging.h
        src/protobuf/src/google/protobuf/stubs/macros.h
        src/protobuf/src/google/protobuf/stubs/map_util.h
        src/protobuf/src/google/protobuf/stubs/mathlimits.cc
        src/protobuf/src/google/protobuf/stubs/mathlimits.h
        src/protobuf/src/google/protobuf/stubs/mathutil.h
        src/protobuf/src/google/protobuf/stubs/mutex.h
        src/protobuf/src/google/protobuf/stubs/once.cc
        src/protobuf/src/google/protobuf/stubs/once.h
        src/protobuf/src/google/protobuf/stubs/platform_macros.h
        src/protobuf/src/google/protobuf/stubs/port.h
        src/protobuf/src/google/protobuf/stubs/scoped_ptr.h
        src/protobuf/src/google/protobuf/stubs/shared_ptr.h
        src/protobuf/src/google/protobuf/stubs/singleton.h
        src/protobuf/src/google/protobuf/stubs/status.cc
        src/protobuf/src/google/protobuf/stubs/status.h
        src/protobuf/src/google/protobuf/stubs/status_macros.h
        src/protobuf/src/google/protobuf/stubs/statusor.cc
        src/protobuf/src/google/protobuf/stubs/statusor.h
        src/protobuf/src/google/protobuf/stubs/stl_util.h
        src/protobuf/src/google/protobuf/stubs/stringpiece.cc
        src/protobuf/src/google/protobuf/stubs/stringpiece.h
        src/protobuf/src/google/protobuf/stubs/stringprintf.cc
        src/protobuf/src/google/protobuf/stubs/stringprintf.h
        src/protobuf/src/google/protobuf/stubs/structurally_valid.cc
        src/protobuf/src/google/protobuf/stubs/strutil.cc
        src/protobuf/src/google/protobuf/stubs/strutil.h
        src/protobuf/src/google/protobuf/stubs/substitute.cc
        src/protobuf/src/google/protobuf/stubs/substitute.h
        src/protobuf/src/google/protobuf/stubs/template_util.h
        src/protobuf/src/google/protobuf/stubs/time.cc
        src/protobuf/src/google/protobuf/stubs/time.h
        src/protobuf/src/google/protobuf/stubs/type_traits.h
        src/protobuf/src/google/protobuf/util/internal/constants.h
        src/protobuf/src/google/protobuf/util/internal/datapiece.cc
        src/protobuf/src/google/protobuf/util/internal/datapiece.h
        src/protobuf/src/google/protobuf/util/internal/default_value_objectwriter.cc
        src/protobuf/src/google/protobuf/util/internal/default_value_objectwriter.h
        src/protobuf/src/google/protobuf/util/internal/error_listener.cc
        src/protobuf/src/google/protobuf/util/internal/error_listener.h
        src/protobuf/src/google/protobuf/util/internal/expecting_objectwriter.h
        src/protobuf/src/google/protobuf/util/internal/field_mask_utility.cc
        src/protobuf/src/google/protobuf/util/internal/field_mask_utility.h
        src/protobuf/src/google/protobuf/util/internal/json_escaping.cc
        src/protobuf/src/google/protobuf/util/internal/json_escaping.h
        src/protobuf/src/google/protobuf/util/internal/json_objectwriter.cc
        src/protobuf/src/google/protobuf/util/internal/json_objectwriter.h
        src/protobuf/src/google/protobuf/util/internal/json_stream_parser.cc
        src/protobuf/src/google/protobuf/util/internal/json_stream_parser.h
        src/protobuf/src/google/protobuf/util/internal/location_tracker.h
        src/protobuf/src/google/protobuf/util/internal/mock_error_listener.h
        src/protobuf/src/google/protobuf/util/internal/object_location_tracker.h
        src/protobuf/src/google/protobuf/util/internal/object_source.h
        src/protobuf/src/google/protobuf/util/internal/object_writer.cc
        src/protobuf/src/google/protobuf/util/internal/object_writer.h
        src/protobuf/src/google/protobuf/util/internal/proto_writer.cc
        src/protobuf/src/google/protobuf/util/internal/proto_writer.h
        src/protobuf/src/google/protobuf/util/internal/protostream_objectsource.cc
        src/protobuf/src/google/protobuf/util/internal/protostream_objectsource.h
        src/protobuf/src/google/protobuf/util/internal/protostream_objectwriter.cc
        src/protobuf/src/google/protobuf/util/internal/protostream_objectwriter.h
        src/protobuf/src/google/protobuf/util/internal/structured_objectwriter.h
        src/protobuf/src/google/protobuf/util/internal/type_info.cc
        src/protobuf/src/google/protobuf/util/internal/type_info.h
        src/protobuf/src/google/protobuf/util/internal/type_info_test_helper.cc
        src/protobuf/src/google/protobuf/util/internal/type_info_test_helper.h
        src/protobuf/src/google/protobuf/util/internal/utility.cc
        src/protobuf/src/google/protobuf/util/internal/utility.h
        src/protobuf/src/google/protobuf/util/field_comparator.cc
        src/protobuf/src/google/protobuf/util/field_comparator.h
        src/protobuf/src/google/protobuf/util/field_mask_util.cc
        src/protobuf/src/google/protobuf/util/field_mask_util.h
        src/protobuf/src/google/protobuf/util/json_util.cc
        src/protobuf/src/google/protobuf/util/json_util.h
        src/protobuf/src/google/protobuf/util/message_differencer.cc
        src/protobuf/src/google/protobuf/util/message_differencer.h
        src/protobuf/src/google/protobuf/util/package_info.h
        src/protobuf/src/google/protobuf/util/time_util.cc
        src/protobuf/src/google/protobuf/util/time_util.h
        src/protobuf/src/google/protobuf/util/type_resolver.h
        src/protobuf/src/google/protobuf/util/type_resolver_util.cc
        src/protobuf/src/google/protobuf/util/type_resolver_util.h
        src/protobuf/src/google/protobuf/any.cc
        src/protobuf/src/google/protobuf/any.h
        src/protobuf/src/google/protobuf/any.pb.cc
        src/protobuf/src/google/protobuf/any.pb.h
        src/protobuf/src/google/protobuf/api.pb.cc
        src/protobuf/src/google/protobuf/api.pb.h
        src/protobuf/src/google/protobuf/arena.cc
        src/protobuf/src/google/protobuf/arena.h
        src/protobuf/src/google/protobuf/arena_test_util.cc
        src/protobuf/src/google/protobuf/arena_test_util.h
        src/protobuf/src/google/protobuf/arenastring.cc
        src/protobuf/src/google/protobuf/arenastring.h
        src/protobuf/src/google/protobuf/descriptor.cc
        src/protobuf/src/google/protobuf/descriptor.h
        src/protobuf/src/google/protobuf/descriptor.pb.cc
        src/protobuf/src/google/protobuf/descriptor.pb.h
        src/protobuf/src/google/protobuf/descriptor_database.cc
        src/protobuf/src/google/protobuf/descriptor_database.h
        src/protobuf/src/google/protobuf/duration.pb.cc
        src/protobuf/src/google/protobuf/duration.pb.h
        src/protobuf/src/google/protobuf/dynamic_message.cc
        src/protobuf/src/google/protobuf/dynamic_message.h
        src/protobuf/src/google/protobuf/empty.pb.cc
        src/protobuf/src/google/protobuf/empty.pb.h
        src/protobuf/src/google/protobuf/extension_set.cc
        src/protobuf/src/google/protobuf/extension_set.h
        src/protobuf/src/google/protobuf/extension_set_heavy.cc
        src/protobuf/src/google/protobuf/field_mask.pb.cc
        src/protobuf/src/google/protobuf/field_mask.pb.h
        src/protobuf/src/google/protobuf/generated_enum_reflection.h
        src/protobuf/src/google/protobuf/generated_enum_util.h
        src/protobuf/src/google/protobuf/generated_message_reflection.cc
        src/protobuf/src/google/protobuf/generated_message_reflection.h
        src/protobuf/src/google/protobuf/generated_message_util.cc
        src/protobuf/src/google/protobuf/generated_message_util.h
        src/protobuf/src/google/protobuf/has_bits.h
        src/protobuf/src/google/protobuf/map.h
        src/protobuf/src/google/protobuf/map_entry.h
        src/protobuf/src/google/protobuf/map_entry_lite.h
        src/protobuf/src/google/protobuf/map_field.cc
        src/protobuf/src/google/protobuf/map_field.h
        src/protobuf/src/google/protobuf/map_field_inl.h
        src/protobuf/src/google/protobuf/map_field_lite.h
        src/protobuf/src/google/protobuf/map_type_handler.h
        src/protobuf/src/google/protobuf/message.cc
        src/protobuf/src/google/protobuf/message.h
        src/protobuf/src/google/protobuf/message_lite.cc
        src/protobuf/src/google/protobuf/message_lite.h
        src/protobuf/src/google/protobuf/metadata.h
        src/protobuf/src/google/protobuf/package_info.h
        src/protobuf/src/google/protobuf/reflection.h
        src/protobuf/src/google/protobuf/reflection_internal.h
        src/protobuf/src/google/protobuf/reflection_ops.cc
        src/protobuf/src/google/protobuf/reflection_ops.h
        src/protobuf/src/google/protobuf/repeated_field.cc
        src/protobuf/src/google/protobuf/repeated_field.h
        src/protobuf/src/google/protobuf/service.cc
        src/protobuf/src/google/protobuf/service.h
        src/protobuf/src/google/protobuf/source_context.pb.cc
        src/protobuf/src/google/protobuf/source_context.pb.h
        src/protobuf/src/google/protobuf/struct.pb.cc
        src/protobuf/src/google/protobuf/struct.pb.h
        src/protobuf/src/google/protobuf/text_format.cc
        src/protobuf/src/google/protobuf/text_format.h
        src/protobuf/src/google/protobuf/timestamp.pb.cc
        src/protobuf/src/google/protobuf/timestamp.pb.h
        src/protobuf/src/google/protobuf/type.pb.cc
        src/protobuf/src/google/protobuf/type.pb.h
        src/protobuf/src/google/protobuf/unknown_field_set.cc
        src/protobuf/src/google/protobuf/unknown_field_set.h
        src/protobuf/src/google/protobuf/wire_format.cc
        src/protobuf/src/google/protobuf/wire_format.h
        src/protobuf/src/google/protobuf/wire_format_lite.cc
        src/protobuf/src/google/protobuf/wire_format_lite.h
        src/protobuf/src/google/protobuf/wire_format_lite_inl.h
        src/protobuf/src/google/protobuf/wrappers.pb.cc
        src/protobuf/src/google/protobuf/wrappers.pb.h
        )
add_library(protobuf STATIC ${PROTOBUF_SRC})
