#!/bin/bash
#
# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
#
set -ex

PROJECT=istio-testing
IMAGE_NAME="gcr.io/${PROJECT}/proxy:experiment"

gcloud docker --authorize-only

bazel run --config=release //src/envoy/mixer:proxy "${IMAGE_NAME}"

gcloud docker -- push "${IMAGE_NAME}"


