#!/bin/bash
#
# Copyright 2016 Istio Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
#
set -ex
set -o errexit
set -o nounset
set -o pipefail

PROJECT="istio-testing"
DATE_PART=$(date +"%Y%m%d")
SHA_PART=$(git show -q HEAD --pretty=format:%h)
DOCKER_TAG="${DATE_PART}-${SHA_PART}"

BAZEL_TARGET_DIR="bazel-bin/src/envoy/mixer"

BAZEL_TARGET="${BAZEL_TARGET_DIR}/envoy"
RELEASE_IMAGE_NAME="gcr.io/${PROJECT}/envoy:${DOCKER_TAG}"
DEBUG_IMAGE_NAME="gcr.io/${PROJECT}/envoy-debug:${DOCKER_TAG}"

gcloud docker --authorize-only


echo Publishing debug docker image
bazel build -c dbg //src/envoy/mixer:envoy
rm -f docker/envoy
cp tools/deb/istio-iptables.sh ${BAZEL_TARGET_DIR}
cp tools/deb/istio-start.sh ${BAZEL_TARGET_DIR}
cp tools/deb/envoy.json ${BAZEL_TARGET_DIR}
cp docker/proxy-* ${BAZEL_TARGET_DIR}
cp docker/Dockerfile.debug ${BAZEL_TARGET_DIR}
docker build -f ${BAZEL_TARGET_DIR}/Dockerfile.debug -t "${DEBUG_IMAGE_NAME}" ${BAZEL_TARGET_DIR}
gcloud docker -- push "${DEBUG_IMAGE_NAME}"

if [[ ${1-} == "debug" ]] ; then
  # Don't push the opt image.
  exit 0
fi

echo Publishing release docker image
bazel build --config=release //src/envoy/mixer:envoy
cp tools/deb/istio-iptables.sh ${BAZEL_TARGET_DIR}
cp tools/deb/istio-start.sh ${BAZEL_TARGET_DIR}
cp tools/deb/envoy.json ${BAZEL_TARGET_DIR}
cp docker/proxy-* ${BAZEL_TARGET_DIR}
cp docker/Dockerfile.release ${BAZEL_TARGET_DIR}
docker build -f ${BAZEL_TARGET_DIR}/Dockerfile.release -t "${RELEASE_IMAGE_NAME}" ${BAZEL_TARGET_DIR}
gcloud docker -- push "${RELEASE_IMAGE_NAME}"

