// Code generated by go-bindata. DO NOT EDIT.
// sources:
// bootstrap/client.yaml.tmpl (2.319kB)
// bootstrap/client_cluster_metadata_precedence.yaml.tmpl (2.318kB)
// bootstrap/otel_stats.yaml.tmpl (293B)
// bootstrap/server.yaml.tmpl (3.279kB)
// bootstrap/stats.yaml.tmpl (2.983kB)
// listener/client.yaml.tmpl (1.149kB)
// listener/client_passthrough.yaml.tmpl (1.611kB)
// listener/internal_outbound.yaml.tmpl (539B)
// listener/server.yaml.tmpl (1.336kB)
// listener/tcp_client.yaml.tmpl (960B)
// listener/tcp_passthrough.yaml.tmpl (979B)
// listener/tcp_server.yaml.tmpl (878B)
// listener/tcp_waypoint_server.yaml.tmpl (802B)
// listener/terminate_connect.yaml.tmpl (4.304kB)

package testdata

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _bootstrapClientYamlTmpl = []byte(`node:
  id: client
  cluster: test-cluster
  metadata: { {{ .Vars.ClientMetadata | fill }} }
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: {{ .Ports.ClientAdmin }}
{{ .Vars.StatsConfig }}
dynamic_resources:
  ads_config:
    api_type: DELTA_GRPC
    transport_api_version: V3
    grpc_services:
    - envoy_grpc:
        cluster_name: xds_cluster
  cds_config:
    ads: {}
    resource_api_version: V3
  lds_config:
    ads: {}
    resource_api_version: V3
static_resources:
  clusters:
  - connect_timeout: 5s
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: {{ .Ports.XDSPort }}
    http2_protocol_options: {}
    name: xds_cluster
  - name: server-outbound-cluster
    connect_timeout: 5s
    type: STATIC
    http2_protocol_options: {}
    {{- if ne .Vars.ElideServerMetadata "true" }}
    metadata:
      filter_metadata:
        istio:
          services:
            - host: server.default.svc.cluster.local
              name: server
              namespace: default
    {{- end }}
    load_assignment:
      cluster_name: server-outbound-cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.2
                port_value: {{ .Ports.ServerPort }}
          {{- if eq .Vars.EnableEndpointMetadata "true" }}
          metadata:
            filter_metadata:
              istio:
                workload: ratings-v1;default;ratings;version-1;server-cluster
          {{- end }}
{{ .Vars.ClientTLSContext | indent 4 }}
{{ .Vars.ClientStaticCluster | indent 2 }}
bootstrap_extensions:
- name: envoy.bootstrap.internal_listener
  typed_config:
    "@type": type.googleapis.com/udpa.type.v1.TypedStruct
    type_url: type.googleapis.com/envoy.extensions.bootstrap.internal_listener.v3.InternalListener
{{- if eq .Vars.EnableMetadataDiscovery "true" }}
- name: metadata_discovery
  typed_config:
    "@type": type.googleapis.com/udpa.type.v1.TypedStruct
    type_url: type.googleapis.com/istio.workload.BootstrapExtension
    value:
      config_source:
        ads: {}
{{- end }}
`)

func bootstrapClientYamlTmplBytes() ([]byte, error) {
	return _bootstrapClientYamlTmpl, nil
}

func bootstrapClientYamlTmpl() (*asset, error) {
	bytes, err := bootstrapClientYamlTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bootstrap/client.yaml.tmpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x94, 0xa3, 0xc3, 0x85, 0xe3, 0xf4, 0x0, 0xd, 0xb7, 0x4, 0x13, 0x35, 0xf0, 0x12, 0xbc, 0x92, 0xf3, 0x53, 0xf2, 0xc1, 0x15, 0x28, 0x76, 0xd, 0xa6, 0x85, 0x16, 0x7a, 0x3a, 0xee, 0xd, 0x34}}
	return a, nil
}

var _bootstrapClient_cluster_metadata_precedenceYamlTmpl = []byte(`node:
  id: client
  cluster: test-cluster
  metadata: { {{ .Vars.ClientMetadata | fill }} }
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: {{ .Ports.ClientAdmin }}
{{ .Vars.StatsConfig }}
dynamic_resources:
  ads_config:
    api_type: DELTA_GRPC
    transport_api_version: V3
    grpc_services:
    - envoy_grpc:
        cluster_name: xds_cluster
  cds_config:
    ads: {}
    resource_api_version: V3
  lds_config:
    ads: {}
    resource_api_version: V3
static_resources:
  clusters:
  - connect_timeout: 5s
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: {{ .Ports.XDSPort }}
    http2_protocol_options: {}
    name: xds_cluster
  - name: server-outbound-cluster
    connect_timeout: 5s
    type: STATIC
    http2_protocol_options: {}
    {{- if ne .Vars.ElideServerMetadata "true" }}
    metadata:
      filter_metadata:
        istio:
          services:
            - host: server.default.svc.cluster.local
              name: server
              namespace: server
    {{- end }}
    load_assignment:
      cluster_name: server-outbound-cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.2
                port_value: {{ .Ports.ServerPort }}
          {{- if eq .Vars.EnableEndpointMetadata "true" }}
          metadata:
            filter_metadata:
              istio:
                workload: ratings-v1;default;ratings;version-1;server-cluster
          {{- end }}
{{ .Vars.ClientTLSContext | indent 4 }}
{{ .Vars.ClientStaticCluster | indent 2 }}
bootstrap_extensions:
- name: envoy.bootstrap.internal_listener
  typed_config:
    "@type": type.googleapis.com/udpa.type.v1.TypedStruct
    type_url: type.googleapis.com/envoy.extensions.bootstrap.internal_listener.v3.InternalListener
{{- if eq .Vars.EnableMetadataDiscovery "true" }}
- name: metadata_discovery
  typed_config:
    "@type": type.googleapis.com/udpa.type.v1.TypedStruct
    type_url: type.googleapis.com/istio.workload.BootstrapExtension
    value:
      config_source:
        ads: {}
{{- end }}
`)

func bootstrapClient_cluster_metadata_precedenceYamlTmplBytes() ([]byte, error) {
	return _bootstrapClient_cluster_metadata_precedenceYamlTmpl, nil
}

func bootstrapClient_cluster_metadata_precedenceYamlTmpl() (*asset, error) {
	bytes, err := bootstrapClient_cluster_metadata_precedenceYamlTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bootstrap/client_cluster_metadata_precedence.yaml.tmpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xe2, 0x23, 0xc3, 0x9d, 0x1f, 0x13, 0x92, 0x17, 0xf0, 0x95, 0xf7, 0xd4, 0xaf, 0xe2, 0xcb, 0x46, 0x5, 0x97, 0xdd, 0xa3, 0x58, 0x14, 0xa1, 0x33, 0xdd, 0x1a, 0x81, 0x71, 0x72, 0xbe, 0xfe, 0x41}}
	return a, nil
}

var _bootstrapOtel_statsYamlTmpl = []byte(`stats_sinks:
- name: otel
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.stat_sinks.open_telemetry.v3.SinkConfig
    grpc_service:
      envoy_grpc:
        cluster_name: otel
stats_config:
  stats_matcher:
    inclusion_list:
      patterns:
      - prefix: "istiocustom."
`)

func bootstrapOtel_statsYamlTmplBytes() ([]byte, error) {
	return _bootstrapOtel_statsYamlTmpl, nil
}

func bootstrapOtel_statsYamlTmpl() (*asset, error) {
	bytes, err := bootstrapOtel_statsYamlTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bootstrap/otel_stats.yaml.tmpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xa6, 0x4f, 0x8c, 0xf, 0xfe, 0xf2, 0x22, 0x8c, 0xd4, 0xd0, 0x8c, 0xc, 0x6, 0x46, 0xa3, 0xec, 0xf9, 0x50, 0x73, 0xee, 0x1a, 0x39, 0xcc, 0x49, 0xa9, 0xfb, 0x60, 0x83, 0x11, 0x67, 0x1, 0x79}}
	return a, nil
}

var _bootstrapServerYamlTmpl = []byte(`node:
  id: server
  cluster: test-cluster
  metadata: { {{ .Vars.ServerMetadata | fill }} }
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: {{ .Ports.ServerAdmin }}
{{ .Vars.StatsConfig }}
dynamic_resources:
  ads_config:
    api_type: DELTA_GRPC
    transport_api_version: V3
    grpc_services:
    - envoy_grpc:
        cluster_name: xds_cluster
  cds_config:
    ads: {}
    resource_api_version: V3
  lds_config:
    ads: {}
    resource_api_version: V3
static_resources:
  clusters:
  - connect_timeout: 5s
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: {{ .Ports.XDSPort }}
    http2_protocol_options: {}
    name: xds_cluster
  - name: server-inbound-cluster
    connect_timeout: 5s
    type: STATIC
    {{- if eq .Vars.UsingGrpcBackend "true" }}
    http2_protocol_options: {}
    {{- end }}
    {{- if ne .Vars.ElideServerMetadata "true" }}
    metadata:
      filter_metadata:
        istio:
          services:
            - host: server.default.svc.cluster.local
              name: server
              namespace: default
    {{- end }}
    load_assignment:
      cluster_name: server-inbound-cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.3
                port_value: {{ .Ports.BackendPort }}
{{ .Vars.ServerStaticCluster | indent 2 }}
{{- if ne .Vars.DisableDirectResponse "true" }}
  listeners:
  - name: staticreply
    address:
      socket_address:
        address: 127.0.0.3
        port_value: {{ .Ports.BackendPort }}
    filter_chains:
    - filters:
      - name: http
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: staticreply
          codec_type: AUTO
          route_config:
            name: staticreply
            virtual_hosts:
            - name: staticreply
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  {{- if .Vars.DirectResponseCode }}
                  status: {{ .Vars.DirectResponseCode }}
                  {{- else }}
                  status: 200
                  {{- end }}
                  body:
                    inline_string: "hello, world!"
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
{{- end }}
bootstrap_extensions:
- name: envoy.bootstrap.internal_listener
  typed_config:
    "@type": type.googleapis.com/udpa.type.v1.TypedStruct
    type_url: type.googleapis.com/envoy.extensions.bootstrap.internal_listener.v3.InternalListener
{{- if eq .Vars.EnableMetadataDiscovery "true" }}
- name: metadata_discovery
  typed_config:
    "@type": type.googleapis.com/udpa.type.v1.TypedStruct
    type_url: type.googleapis.com/istio.workload.BootstrapExtension
    value:
      config_source:
        ads: {}
{{- end }}
`)

func bootstrapServerYamlTmplBytes() ([]byte, error) {
	return _bootstrapServerYamlTmpl, nil
}

func bootstrapServerYamlTmpl() (*asset, error) {
	bytes, err := bootstrapServerYamlTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bootstrap/server.yaml.tmpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x4e, 0xf5, 0x72, 0x35, 0x1b, 0xb2, 0x7d, 0xd6, 0xb4, 0x44, 0xdb, 0xf7, 0x9a, 0xdf, 0x28, 0xce, 0xe9, 0xe5, 0x92, 0xf8, 0xe2, 0x95, 0x8d, 0xc, 0xeb, 0x4f, 0x13, 0x61, 0x66, 0x8d, 0xa8, 0x6d}}
	return a, nil
}

var _bootstrapStatsYamlTmpl = []byte(`stats_config:
  use_all_default_tags: true
  stats_tags:
  - tag_name: "reporter"
    regex: "(reporter=\\.=(.*?);\\.;)"
  - tag_name: "source_namespace"
    regex: "(source_namespace=\\.=(.*?);\\.;)"
  - tag_name: "source_workload"
    regex: "(source_workload=\\.=(.*?);\\.;)"
  - tag_name: "source_canonical_service"
    regex: "(source_canonical_service=\\.=(.*?);\\.;)"
  - tag_name: "source_canonical_revision"
    regex: "(source_canonical_revision=\\.=(.*?);\\.;)"
  - tag_name: "source_workload_namespace"
    regex: "(source_workload_namespace=\\.=(.*?);\\.;)"
  - tag_name: "source_principal"
    regex: "(source_principal=\\.=(.*?);\\.;)"
  - tag_name: "source_app"
    regex: "(source_app=\\.=(.*?);\\.;)"
  - tag_name: "source_version"
    regex: "(source_version=\\.=(.*?);\\.;)"
  - tag_name: "destination_namespace"
    regex: "(destination_namespace=\\.=(.*?);\\.;)"
  - tag_name: "source_cluster"
    regex: "(source_cluster=\\.=(.*?);\\.;)"
  - tag_name: "destination_workload"
    regex: "(destination_workload=\\.=(.*?);\\.;)"
  - tag_name: "destination_workload_namespace"
    regex: "(destination_workload_namespace=\\.=(.*?);\\.;)"
  - tag_name: "destination_principal"
    regex: "(destination_principal=\\.=(.*?);\\.;)"
  - tag_name: "destination_app"
    regex: "(destination_app=\\.=(.*?);\\.;)"
  - tag_name: "destination_version"
    regex: "(destination_version=\\.=(.*?);\\.;)"
  - tag_name: "destination_service"
    regex: "(destination_service=\\.=(.*?);\\.;)"
  - tag_name: "destination_canonical_service"
    regex: "(destination_canonical_service=\\.=(.*?);\\.;)"
  - tag_name: "destination_canonical_revision"
    regex: "(destination_canonical_revision=\\.=(.*?);\\.;)"
  - tag_name: "destination_service_name"
    regex: "(destination_service_name=\\.=(.*?);\\.;)"
  - tag_name: "destination_service_namespace"
    regex: "(destination_service_namespace=\\.=(.*?);\\.;)"
  - tag_name: "destination_cluster"
    regex: "(destination_cluster=\\.=(.*?);\\.;)"
  - tag_name: "request_protocol"
    regex: "(request_protocol=\\.=(.*?);\\.;)"
  - tag_name: "response_code"
    regex: "(response_code=\\.=(.*?);\\.;)|_rq(_(\\.d{3}))$"
  - tag_name: "grpc_response_status"
    regex: "(grpc_response_status=\\.=(.*?);\\.;)"
  - tag_name: "response_flags"
    regex: "(response_flags=\\.=(.*?);\\.;)"
  - tag_name: "connection_security_policy"
    regex: "(connection_security_policy=\\.=(.*?);\\.;)"
# Extra regexes used for configurable metrics
  - tag_name: "configurable_metric_a"
    regex: "(configurable_metric_a=\\.=(.*?);\\.;)"
  - tag_name: "configurable_metric_b"
    regex: "(configurable_metric_b=\\.=(.*?);\\.;)"
  - tag_name: "route_name"
    regex: "(route_name=\\.=(.*?);\\.;)"
# Internal monitoring
  - tag_name: "cache"
    regex: "(cache\\.(.*?)\\.)"
  - tag_name: "component"
    regex: "(component\\.(.*?)\\.)"
  - tag_name: "tag"
    regex: "(tag\\.(.*?);\\.)"
  - tag_name: "wasm_filter"
    regex: "(wasm_filter\\.(.*?)\\.)"
`)

func bootstrapStatsYamlTmplBytes() ([]byte, error) {
	return _bootstrapStatsYamlTmpl, nil
}

func bootstrapStatsYamlTmpl() (*asset, error) {
	bytes, err := bootstrapStatsYamlTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bootstrap/stats.yaml.tmpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x62, 0x58, 0x44, 0xf7, 0xe2, 0x88, 0x48, 0x3c, 0x1c, 0x13, 0x4b, 0xf8, 0x45, 0x34, 0xd3, 0xe, 0x83, 0x30, 0xb8, 0x0, 0xf5, 0x15, 0xfc, 0x19, 0x28, 0x5e, 0x6e, 0xd5, 0x9f, 0x5c, 0x88, 0x4}}
	return a, nil
}

var _listenerClientYamlTmpl = []byte(`{{- if ne .Vars.ClientListeners "" }}
{{ .Vars.ClientListeners }}
{{- else }}
name: client
traffic_direction: OUTBOUND
address:
  socket_address:
    address: 127.0.0.1
    port_value: {{ .Ports.ClientPort }}
filter_chains:
- filters:
  - name: http
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
      codec_type: AUTO
      stat_prefix: client
{{ .Vars.ClientHTTPAccessLogs | fill | indent 6 }}
      http_filters:
{{ .Vars.ClientHTTPFilters | fill | indent 6 }}
      - name: envoy.filters.http.router
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      route_config:
        name: client
        virtual_hosts:
        - name: client
          domains: ["*"]
          routes:
          - name: client_route
            match: { prefix: / }
            route:
              {{- if .Vars.ServerClusterName }}
              cluster: {{ .Vars.ServerClusterName}}
              {{- else }}
              cluster: server-outbound-cluster
              {{- end }}
              timeout: 0s
{{- end }}
`)

func listenerClientYamlTmplBytes() ([]byte, error) {
	return _listenerClientYamlTmpl, nil
}

func listenerClientYamlTmpl() (*asset, error) {
	bytes, err := listenerClientYamlTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "listener/client.yaml.tmpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x1, 0xe2, 0xb9, 0x3a, 0x5d, 0xc4, 0x7d, 0xe6, 0x80, 0x76, 0x89, 0x64, 0x42, 0x32, 0x9c, 0xea, 0xcb, 0x4a, 0xca, 0x14, 0xaf, 0x84, 0x15, 0xfb, 0x87, 0x91, 0x39, 0x37, 0xd6, 0x26, 0x94, 0x6d}}
	return a, nil
}

var _listenerClient_passthroughYamlTmpl = []byte(`name: client
traffic_direction: OUTBOUND
address:
  socket_address:
    address: 127.0.0.1
    port_value: {{ .Ports.ClientPort }}
filter_chains:
- filters:
  - name: http
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
      codec_type: AUTO
      stat_prefix: client
      http_filters:
      - name: connect_authority
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.set_filter_state.v3.Config
          value:
            on_request_headers:
            - object_key: envoy.filters.listener.original_dst.local_ip
              format_string:
                text_format_source:
                  inline_string: "%REQ(:AUTHORITY)%"
                omit_empty_values: true
              shared_with_upstream: ONCE
              skip_if_empty: true
            - object_key: envoy.filters.listener.original_dst.remote_ip
              format_string:
                text_format_source:
                  inline_string: "%DOWNSTREAM_REMOTE_ADDRESS%"
              shared_with_upstream: ONCE
      - name: envoy.filters.http.router
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      route_config:
        name: client
        virtual_hosts:
        - name: client
          domains: ["*"]
          routes:
          - name: client_route
            match: { prefix: / }
            route:
              cluster: tcp_passthrough
              timeout: 0s
`)

func listenerClient_passthroughYamlTmplBytes() ([]byte, error) {
	return _listenerClient_passthroughYamlTmpl, nil
}

func listenerClient_passthroughYamlTmpl() (*asset, error) {
	bytes, err := listenerClient_passthroughYamlTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "listener/client_passthrough.yaml.tmpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x9e, 0x32, 0x92, 0xe4, 0x31, 0xdd, 0xde, 0x5e, 0x1a, 0x2e, 0x8, 0xa, 0x40, 0xe8, 0xfb, 0x79, 0xbb, 0xb6, 0xe7, 0xa2, 0x53, 0x11, 0x4f, 0x7e, 0xe7, 0x98, 0x7, 0x8b, 0x23, 0x55, 0x69, 0x4c}}
	return a, nil
}

var _listenerInternal_outboundYamlTmpl = []byte(`name: internal_outbound
internal_listener: {}
listener_filters:
- name: set_dst_address
  typed_config:
    "@type": type.googleapis.com/udpa.type.v1.TypedStruct
    type_url: type.googleapis.com/envoy.extensions.filters.listener.original_dst.v3.OriginalDst
filter_chains:
- filters:
  - name: tcp_proxy
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
      cluster: original_dst
      tunneling_config:
        hostname: "%DOWNSTREAM_LOCAL_ADDRESS%"
      stat_prefix: outbound
`)

func listenerInternal_outboundYamlTmplBytes() ([]byte, error) {
	return _listenerInternal_outboundYamlTmpl, nil
}

func listenerInternal_outboundYamlTmpl() (*asset, error) {
	bytes, err := listenerInternal_outboundYamlTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "listener/internal_outbound.yaml.tmpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x44, 0x13, 0x5a, 0xde, 0x24, 0x88, 0x35, 0x23, 0x9e, 0xc5, 0xc4, 0x93, 0xad, 0x70, 0x64, 0xf3, 0x80, 0x9d, 0x88, 0x5a, 0x73, 0x87, 0x76, 0x28, 0x9e, 0x20, 0x41, 0xb5, 0x8b, 0xfe, 0x95, 0x58}}
	return a, nil
}

var _listenerServerYamlTmpl = []byte(`{{- if ne .Vars.ServerListeners "" }}
{{ .Vars.ServerListeners }}
{{- else }}
{{- if ne .Vars.ServerInternalAddress "" }}
name: {{ .Vars.ServerInternalAddress }}
{{- else }}
name: server
{{- end }}
traffic_direction: INBOUND
{{- if ne .Vars.ServerInternalAddress "" }}
internal_listener: {}
{{- else }}
address:
  socket_address:
    address: 127.0.0.2
    port_value: {{ .Ports.ServerPort }}
{{- end }}
filter_chains:
- filters:
{{ .Vars.ServerNetworkFilters | fill | indent 2 }}
  - name: http
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
      codec_type: AUTO
      stat_prefix: server
{{ .Vars.ServerHTTPAccessLogs | fill | indent 6 }}
      http_filters:
{{ .Vars.ServerHTTPFilters | fill | indent 6 }}
      - name: envoy.filters.http.router
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      route_config:
        name: server
        virtual_hosts:
        - name: server
          domains: ["*"]
          routes:
          - name: server_route
            match: { prefix: / }
            route:
              cluster: server-inbound-cluster
              timeout: 0s
{{ .Vars.ServerRouteRateLimits | fill | indent 14 }}
{{ .Vars.ServerTLSContext | indent 2 }}
{{- end }}
`)

func listenerServerYamlTmplBytes() ([]byte, error) {
	return _listenerServerYamlTmpl, nil
}

func listenerServerYamlTmpl() (*asset, error) {
	bytes, err := listenerServerYamlTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "listener/server.yaml.tmpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xa2, 0x77, 0x1a, 0x40, 0xa1, 0xe2, 0xb5, 0x5, 0x34, 0x18, 0x91, 0x7c, 0xc3, 0xf6, 0xcd, 0x22, 0x86, 0xdd, 0x86, 0x5a, 0x4f, 0xd0, 0xe5, 0x9b, 0x8, 0x18, 0xb2, 0x5, 0x5a, 0xb9, 0x23, 0x84}}
	return a, nil
}

var _listenerTcp_clientYamlTmpl = []byte(`name: client
traffic_direction: OUTBOUND
address:
  socket_address:
    address: 127.0.0.1
    port_value: {{ .Ports.ClientPort }}
listener_filters:
- name: "envoy.filters.listener.tls_inspector"
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
- name: "envoy.filters.listener.http_inspector"
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.listener.http_inspector.v3.HttpInspector
filter_chains:
- filters:
{{ .Vars.ClientNetworkFilters | fill | indent 2 }}
  - name: tcp_proxy
    typed_config:
      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
      type_url: envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
      value:
        stat_prefix: outbound_tcp
        {{- if .Vars.ServerClusterName }}
        cluster: {{ .Vars.ServerClusterName}}
        {{- else }}
        cluster: outbound|9080|tcp|server.default.svc.cluster.local
        {{- end }}
`)

func listenerTcp_clientYamlTmplBytes() ([]byte, error) {
	return _listenerTcp_clientYamlTmpl, nil
}

func listenerTcp_clientYamlTmpl() (*asset, error) {
	bytes, err := listenerTcp_clientYamlTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "listener/tcp_client.yaml.tmpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x4d, 0x34, 0x2f, 0xba, 0xb0, 0xc3, 0x24, 0xd2, 0x3, 0xd1, 0xf, 0xf2, 0xd, 0xe3, 0xdf, 0x4c, 0xf8, 0x70, 0x8a, 0x65, 0x98, 0x34, 0xd0, 0x30, 0xd8, 0x9, 0xa1, 0xe1, 0xae, 0x4d, 0xc8, 0xb4}}
	return a, nil
}

var _listenerTcp_passthroughYamlTmpl = []byte(`name: tcp_passthrough
internal_listener: {}
listener_filters:
- name: set_dst_address
  typed_config:
    "@type": type.googleapis.com/udpa.type.v1.TypedStruct
    type_url: type.googleapis.com/envoy.extensions.filters.listener.original_dst.v3.OriginalDst
filter_chains:
- filters:
  - name: connect_authority
    typed_config:
      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
      type_url: type.googleapis.com/envoy.extensions.filters.network.set_filter_state.v3.Config
      value:
        on_new_connection:
        - object_key: envoy.filters.listener.original_dst.local_ip
          format_string:
            text_format_source:
              inline_string: "%FILTER_STATE(envoy.filters.listener.original_dst.local_ip:PLAIN)%"
          shared_with_upstream: ONCE
  - name: tcp_proxy
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
      cluster: internal_outbound
      stat_prefix: tcp_passthrough
`)

func listenerTcp_passthroughYamlTmplBytes() ([]byte, error) {
	return _listenerTcp_passthroughYamlTmpl, nil
}

func listenerTcp_passthroughYamlTmpl() (*asset, error) {
	bytes, err := listenerTcp_passthroughYamlTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "listener/tcp_passthrough.yaml.tmpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x96, 0xf0, 0xe7, 0x31, 0xa2, 0x38, 0xe, 0xf3, 0xb8, 0x50, 0xa6, 0x1, 0x46, 0xdf, 0xf8, 0xa8, 0xaa, 0x9c, 0x90, 0xa, 0x76, 0xd0, 0x8, 0x95, 0x58, 0xb1, 0x28, 0x8b, 0x99, 0xe3, 0x6d, 0xaa}}
	return a, nil
}

var _listenerTcp_serverYamlTmpl = []byte(`name: server
traffic_direction: INBOUND
address:
  socket_address:
    address: 127.0.0.2
    port_value: {{ .Ports.ServerPort }}
listener_filters:
- name: "envoy.filters.listener.tls_inspector"
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
- name: "envoy.filters.listener.http_inspector"
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.listener.http_inspector.v3.HttpInspector
filter_chains:
- filters:
{{ .Vars.ServerNetworkFilters | fill | indent 2 }}
  - name: tcp_proxy
    typed_config:
      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
      type_url: envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
      value:
        stat_prefix: inbound_tcp
        cluster: inbound|9080|tcp|server.default.svc.cluster.local
{{ .Vars.ServerListenerTLSContext | indent 2 }}
`)

func listenerTcp_serverYamlTmplBytes() ([]byte, error) {
	return _listenerTcp_serverYamlTmpl, nil
}

func listenerTcp_serverYamlTmpl() (*asset, error) {
	bytes, err := listenerTcp_serverYamlTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "listener/tcp_server.yaml.tmpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xfc, 0x8f, 0x88, 0xbe, 0x5c, 0x69, 0x73, 0xfe, 0x78, 0x88, 0xf1, 0x48, 0xbf, 0xf8, 0x34, 0xb5, 0x6a, 0xd2, 0x48, 0x9f, 0xf4, 0x78, 0x24, 0x93, 0xd2, 0x62, 0xef, 0x40, 0xf1, 0x62, 0x9f, 0xe6}}
	return a, nil
}

var _listenerTcp_waypoint_serverYamlTmpl = []byte(`{{- if ne .Vars.ServerListeners "" }}
{{ .Vars.ServerListeners }}
{{- else }}
{{- if ne .Vars.ServerInternalAddress "" }}
name: {{ .Vars.ServerInternalAddress }}
{{- else }}
name: server
{{- end }}
traffic_direction: INBOUND
{{- if ne .Vars.ServerInternalAddress "" }}
internal_listener: {}
{{- else }}
address:
  socket_address:
    address: 127.0.0.2
    port_value: {{ .Ports.ServerPort }}
{{- end }}
filter_chains:
- filters:
{{ .Vars.ServerNetworkFilters | fill | indent 2 }}
  - name: tcp_proxy
    typed_config:
      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
      type_url: envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
      value:
        stat_prefix: server_inbound_tcp
        cluster: server-inbound-cluster
{{ .Vars.ServerListenerTLSContext | indent 2 }}
{{- end }}
`)

func listenerTcp_waypoint_serverYamlTmplBytes() ([]byte, error) {
	return _listenerTcp_waypoint_serverYamlTmpl, nil
}

func listenerTcp_waypoint_serverYamlTmpl() (*asset, error) {
	bytes, err := listenerTcp_waypoint_serverYamlTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "listener/tcp_waypoint_server.yaml.tmpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xa1, 0xd5, 0x7f, 0x3b, 0x62, 0xfd, 0xa5, 0x57, 0x3d, 0xdd, 0x3d, 0xd7, 0x40, 0x28, 0x8e, 0xe9, 0xf9, 0x5a, 0x73, 0x3e, 0xf6, 0xed, 0xde, 0xbc, 0xd0, 0xe3, 0x0, 0x31, 0xe7, 0xb2, 0x82, 0xa7}}
	return a, nil
}

var _listenerTerminate_connectYamlTmpl = []byte(`name: terminate_connect
address:
  socket_address:
{{ if eq .Vars.quic "true" }}
    protocol: UDP
{{ end }}
    address: 127.0.0.2
    port_value: {{ .Ports.ServerTunnelPort }}
{{ if eq .Vars.quic "true" }}
udp_listener_config:
  quic_options: {}
  downstream_socket_config:
    prefer_gro: true
{{ end }}
filter_chains:
- filters:
  # Capture SSL info for the internal listener passthrough
  - name: envoy.filters.network.http_connection_manager
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
      stat_prefix: terminate_connect
{{ if eq .Vars.quic "true" }}
      codec_type: HTTP3
{{ end }}
      route_config:
        name: local_route
        virtual_hosts:
        - name: local_service
          domains:
          - "*"
          routes:
          - match:
              connect_matcher:
                {}
            route:
              cluster: internal_inbound
              upgrade_configs:
              - upgrade_type: CONNECT
                connect_config:
                  {}
      http_filters:
      {{ if eq .Vars.quic "true" }}
      # TODO: accessing uriSanPeerCertificates() triggers a crash in quiche version.
      {{ else }}
      - name: authn
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.set_filter_state.v3.Config
          value:
            on_request_headers:
            - object_key: io.istio.peer_principal
              factory_key: envoy.string
              format_string:
                text_format_source:
                  inline_string: "%DOWNSTREAM_PEER_URI_SAN%"
              shared_with_upstream: ONCE
            - object_key: io.istio.local_principal
              factory_key: envoy.string
              format_string:
                text_format_source:
                  inline_string: "%DOWNSTREAM_LOCAL_URI_SAN%"
              shared_with_upstream: ONCE
      {{ end }}
      - name: peer_metadata
        typed_config:
          "@type": type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/io.istio.http.peer_metadata.Config
          value:
            downstream_discovery:
            - workload_discovery: {}
            shared_with_upstream: true
      - name: envoy.filters.http.router
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      http2_protocol_options:
        allow_connect: true
      upgrade_configs:
      - upgrade_type: CONNECT
  transport_socket:
{{ if eq .Vars.quic "true" }}
    name: quic
    typed_config:
      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
      type_url: type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicDownstreamTransport
      value:
        downstream_tls_context:
          common_tls_context:
            tls_certificate_sds_secret_configs:
              name: server
              sds_config:
                api_config_source:
                  api_type: GRPC
                  grpc_services:
                  - envoy_grpc:
                      cluster_name: xds_cluster
                  set_node_on_first_message_only: true
                  transport_api_version: V3
                resource_api_version: V3
            validation_context:
              trusted_ca: { filename: "testdata/certs/root.cert" }
#         require_client_certificate: true # XXX: This setting is ignored ATM per @danzh.
{{ else }}
    name: tls
    typed_config:
      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
      type_url: envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
      value:
        common_tls_context:
          tls_certificate_sds_secret_configs:
            name: server
            sds_config:
              api_config_source:
                api_type: GRPC
                grpc_services:
                - envoy_grpc:
                    cluster_name: xds_cluster
                set_node_on_first_message_only: true
                transport_api_version: V3
              resource_api_version: V3
          validation_context:
            trusted_ca: { filename: "testdata/certs/root.cert" }
        require_client_certificate: true
{{ end }}
`)

func listenerTerminate_connectYamlTmplBytes() ([]byte, error) {
	return _listenerTerminate_connectYamlTmpl, nil
}

func listenerTerminate_connectYamlTmpl() (*asset, error) {
	bytes, err := listenerTerminate_connectYamlTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "listener/terminate_connect.yaml.tmpl", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xa1, 0x2b, 0xf0, 0x75, 0x1f, 0x63, 0x25, 0x2d, 0xee, 0xab, 0xc2, 0x58, 0x8c, 0xa, 0x50, 0xba, 0x99, 0x30, 0x46, 0xc1, 0x67, 0x42, 0xcb, 0x4, 0xaa, 0x91, 0xfa, 0x98, 0xb5, 0x16, 0xb7, 0x3f}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"bootstrap/client.yaml.tmpl":                             bootstrapClientYamlTmpl,
	"bootstrap/client_cluster_metadata_precedence.yaml.tmpl": bootstrapClient_cluster_metadata_precedenceYamlTmpl,
	"bootstrap/otel_stats.yaml.tmpl":                         bootstrapOtel_statsYamlTmpl,
	"bootstrap/server.yaml.tmpl":                             bootstrapServerYamlTmpl,
	"bootstrap/stats.yaml.tmpl":                              bootstrapStatsYamlTmpl,
	"listener/client.yaml.tmpl":                              listenerClientYamlTmpl,
	"listener/client_passthrough.yaml.tmpl":                  listenerClient_passthroughYamlTmpl,
	"listener/internal_outbound.yaml.tmpl":                   listenerInternal_outboundYamlTmpl,
	"listener/server.yaml.tmpl":                              listenerServerYamlTmpl,
	"listener/tcp_client.yaml.tmpl":                          listenerTcp_clientYamlTmpl,
	"listener/tcp_passthrough.yaml.tmpl":                     listenerTcp_passthroughYamlTmpl,
	"listener/tcp_server.yaml.tmpl":                          listenerTcp_serverYamlTmpl,
	"listener/tcp_waypoint_server.yaml.tmpl":                 listenerTcp_waypoint_serverYamlTmpl,
	"listener/terminate_connect.yaml.tmpl":                   listenerTerminate_connectYamlTmpl,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"bootstrap": {nil, map[string]*bintree{
		"client.yaml.tmpl": {bootstrapClientYamlTmpl, map[string]*bintree{}},
		"client_cluster_metadata_precedence.yaml.tmpl": {bootstrapClient_cluster_metadata_precedenceYamlTmpl, map[string]*bintree{}},
		"otel_stats.yaml.tmpl":                         {bootstrapOtel_statsYamlTmpl, map[string]*bintree{}},
		"server.yaml.tmpl":                             {bootstrapServerYamlTmpl, map[string]*bintree{}},
		"stats.yaml.tmpl":                              {bootstrapStatsYamlTmpl, map[string]*bintree{}},
	}},
	"listener": {nil, map[string]*bintree{
		"client.yaml.tmpl":              {listenerClientYamlTmpl, map[string]*bintree{}},
		"client_passthrough.yaml.tmpl":  {listenerClient_passthroughYamlTmpl, map[string]*bintree{}},
		"internal_outbound.yaml.tmpl":   {listenerInternal_outboundYamlTmpl, map[string]*bintree{}},
		"server.yaml.tmpl":              {listenerServerYamlTmpl, map[string]*bintree{}},
		"tcp_client.yaml.tmpl":          {listenerTcp_clientYamlTmpl, map[string]*bintree{}},
		"tcp_passthrough.yaml.tmpl":     {listenerTcp_passthroughYamlTmpl, map[string]*bintree{}},
		"tcp_server.yaml.tmpl":          {listenerTcp_serverYamlTmpl, map[string]*bintree{}},
		"tcp_waypoint_server.yaml.tmpl": {listenerTcp_waypoint_serverYamlTmpl, map[string]*bintree{}},
		"terminate_connect.yaml.tmpl":   {listenerTerminate_connectYamlTmpl, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = os.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
